---
name: CI on Main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: run cargo build
        run: cargo build --all-features
